=== duongtu80/geoengine/trunk/geoprocess/src/main/resources/conf/schema/geomodel/processingMeta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.geodata.cn/models/geoprocessing" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:geo="http://www.geodata.cn/models/geoprocessing">

    <element name="processes" type="geo:processesType"></element>
    
    <complexType name="processesType">
    	<sequence>
    		<element ref="geo:process" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="processType">
    	<sequence>
    		<element name="id" type="string"></element>
    		<element name="title" type="string"></element>
    		<element name="describe" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="tags" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
            <element name="metadata" type="anyURI" maxOccurs="unbounded" minOccurs="0"></element>
            <element name="inputs" type="geo:inputsType"></element>
    		<element name="outputs" type="geo:outputsType"></element>

    	</sequence>
    </complexType>
    

    <complexType name="inputsType">
    	<sequence>
    		<element name="input" type="geo:valueType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="valueType">
    	<sequence>
    		<element name="id" type="string"></element>
    		<element name="title" type="string"></element>
    		<element name="describe" type="string"></element>
            <element name="tags" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="metadata" type="anyURI" maxOccurs="1" minOccurs="0"></element>
    		<element name="category" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="occurs" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="outputsType">
    	<sequence>
    		<element name="output" type="geo:valueType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <element name="process" type="geo:processType"></element>
</schema>

=== duongtu80/geoengine/trunk/model.landfire/src/main/resources/META-INF/metadata/landfireModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<geo:processes xmlns:geo="http://www.geodata.cn/models/geoprocessing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.geodata.cn/models/geoprocessing ../../../../../../geoprocess/src/main/resources/conf/schema/geomodel/processingMeta.xsd ">
	<geo:process>
		<geo:id>landfire.samples</geo:id>
		<geo:title>Collect Samples</geo:title>
		<geo:describe>Collect samples</geo:describe>
		<geo:inputs>
			<geo:input>
				<geo:id>datasetId</geo:id>
				<geo:title>Dataset Id</geo:title>
				<geo:describe>Dataset Id</geo:describe>
				<geo:category>string</geo:category>
			</geo:input>
			<geo:input>
				<geo:id>maxCount</geo:id>
				<geo:title>Maximize Count</geo:title>
				<geo:describe>Maximize Count</geo:describe>
				<geo:category>int</geo:category>
			</geo:input>
			<geo:input>
				<geo:id>minDistance</geo:id>
				<geo:title>Minimize Distance</geo:title>
				<geo:describe>Minimize Distance</geo:describe>
				<geo:category>double</geo:category>
			</geo:input>
		</geo:inputs>
		<geo:outputs>
			<geo:output>
				<geo:id>samples</geo:id>
				<geo:title>Samples</geo:title>
				<geo:describe>Samples</geo:describe>
				<geo:category>featureCollection</geo:category>
			</geo:output>
		</geo:outputs>
	</geo:process>
</geo:processes>

=== duongtu80/geoengine/trunk/model.sealevel/src/main/resources/META-INF/metadata/swampModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<geo:processes xmlns:geo="http://www.geodata.cn/models/geoprocessing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.geodata.cn/models/geoprocessing ../../../../../../models/src/main/resources/conf/schema/geomodel/processingMeta.xsd ">
	<geo:process>
		<geo:id>swamp.cities</geo:id>
		<geo:title>Swamp Cities</geo:title>
		<geo:tags>swamp</geo:tags>
		<geo:inputs>
			<geo:input>
				<geo:id>rise</geo:id>
				<geo:title>Sea level rise</geo:title>
				<geo:describe>Sea level rise</geo:describe>
				<geo:category>double</geo:category>
			</geo:input>
			<geo:input>
				<geo:id>cities</geo:id>
				<geo:title>Cities</geo:title>
				<geo:describe>Cities</geo:describe>
				<geo:category>featureCollection</geo:category>
			</geo:input>
		</geo:inputs>
		<geo:outputs>
			<geo:output>
				<geo:id>swamp</geo:id>
				<geo:title>Swampped cities</geo:title>
				<geo:describe>Swampped cities</geo:describe>
				<geo:category>featureCollection</geo:category>
			</geo:output>
		</geo:outputs>
	</geo:process>
</geo:processes>
