=== duongtu80/geoengine/branches/geoengine-1.0/geoprocess/src/main/resources/conf/schema/geomodel/processingMeta.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by Fengm (EMBRACE) -->
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<schema xmlns:geo="http://www.geodata.cn/models/geoprocessing" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.geodata.cn/models/geoprocessing" elementFormDefault="qualified">
	<element name="model" type="geo:modelType"/>
	<complexType name="modelType">
		<sequence>
			<element name="id" type="string"/>
			<element name="title" type="string"/>
			<element name="metadata" type="anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<element name="provider" minOccurs="0">
				<complexType>
					<choice>
						<element name="IndividualName" type="string" minOccurs="0"/>
						<element name="OrganisationName" type="string" minOccurs="0"/>
						<element name="PositionName" type="string" minOccurs="0"/>
						<element name="Role" type="string" minOccurs="0"/>
						<element name="ContactInfo" minOccurs="0">
							<complexType>
								<sequence/>
							</complexType>
						</element>
					</choice>
				</complexType>
			</element>
			<element name="describe" type="string" minOccurs="0"/>
			<element ref="geo:process" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="processType">
		<sequence>
			<element name="id" type="string"/>
			<element name="title" type="string"/>
			<element name="describe" type="string" minOccurs="0"/>
			<element name="tags" type="string" minOccurs="0" maxOccurs="unbounded"/>
			<element name="metadata" type="anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<element name="inputs" type="geo:inputsType"/>
			<element name="outputs" type="geo:outputsType"/>
		</sequence>
	</complexType>
	<complexType name="inputsType">
		<sequence>
			<element name="input" type="geo:valueType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="valueType">
		<sequence>
			<element name="id" type="string"/>
			<element name="title" type="string"/>
			<element name="describe" type="string" minOccurs="0"/>
			<element name="tags" type="string" minOccurs="0"/>
			<element name="crs" type="string" minOccurs="0"/>
			<element name="metadata" type="anyURI" minOccurs="0"/>
			<element name="category" type="string" maxOccurs="unbounded"/>
			<element name="occurs" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="outputsType">
		<sequence>
			<element name="output" type="geo:valueType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<element name="process" type="geo:processType"/>
</schema>

=== duongtu80/geoengine/trunk/model.sealevel/src/main/resources/META-INF/metadata/swampMetadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<geo:model xmlns:geo="http://www.geodata.cn/models/geoprocessing"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.geodata.cn/models/geoprocessing ../../../../../../geoprocess/src/main/resources/conf/schema/geomodel/processingMeta.xsd ">
	<geo:id>Swamp</geo:id>
	<geo:title>海平面上升模型</geo:title>
	<geo:process>
		<geo:id>Cities</geo:id>
		<geo:title>提取受影响城市</geo:title>
		<geo:tags>swamp, city</geo:tags>
		<geo:inputs>
			<geo:input>
				<geo:id>Rise</geo:id>
				<geo:title>海平面上升高度</geo:title>
				<geo:describe>与2000年全球海平面高度相比较的海平面相对上升高度</geo:describe>
				<geo:category>double</geo:category>
			</geo:input>
			<geo:input>
				<geo:id>Cities</geo:id>
				<geo:title>主要城市</geo:title>
				<geo:describe>全球主要城市分布数据集</geo:describe>
				<geo:category>featureCollection</geo:category>
			</geo:input>
		</geo:inputs>
		<geo:outputs>
			<geo:output>
				<geo:id>Swamp</geo:id>
				<geo:title>受影响城市</geo:title>
				<geo:describe>海平面上升后的受影响城市</geo:describe>
				<geo:category>featureCollection</geo:category>
			</geo:output>
		</geo:outputs>
	</geo:process>
	<geo:process>
		<geo:id>Report</geo:id>
		<geo:title>受灾分析</geo:title>
		<geo:tags>swamp</geo:tags>
		<geo:inputs>
			<geo:input>
				<geo:id>CityId</geo:id>
				<geo:title>城市</geo:title>
				<geo:describe>城市的代码</geo:describe>
				<geo:category>string</geo:category>
			</geo:input>
			<geo:input>
				<geo:id>Cities</geo:id>
				<geo:title>主要城市</geo:title>
				<geo:describe>全球主要城市分布数据集</geo:describe>
				<geo:category>featureCollection</geo:category>
			</geo:input>
		</geo:inputs>
		<geo:outputs>
			<geo:output>
				<geo:id>Report</geo:id>
				<geo:title>分析结果</geo:title>
				<geo:describe>海平面上升后对该城市的影响分析结果</geo:describe>
				<geo:category>featureCollection</geo:category>
			</geo:output>
		</geo:outputs>
	</geo:process>
</geo:model>
